services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  app:
    depends_on:
      db:
        condition: service_started
    build: ./sreality
    ports:
      - "8080:8080"
